server:
  port: ${PORT:7503}

spring:
  datasource:
    url: jdbc:postgresql://localhost:10001/emss
    username: msg_user
    password: msg_user
  flyway:
    url: jdbc:postgresql://localhost:10001/emss
    user: msg_user
    password: msg_user
    schemas: posts
    baseline-on-migrate: true